### PR TITLE
Dev/1.0.0

### PR DESCRIPTION
**Pull request by alexjhawk**

### CODE REVIEW

**Comment by alexjhawk** [comment]
@it-hms This does not yet include the mentioned injection of an argument to indicate that the multi-loader started the application. I have already begun parallel work to add that in a follow-up PR alongside testing against relevant applications to ensure the argument is handled correctly.

**Review by it-hms — APPROVED** [review]

**Review by TomKimsey — APPROVED** [review]
What is the performance like? I dont think i saw any documentation mentioning any limitations.

**Comment by alexjhawk** [comment]
> What is the performance like? I dont think i saw any documentation mentioning any limitations.

I didn't do any explicit performance testing, but in general, there should be no hit. Once each main() is invoked, the multi-loader itself finishes. Aside from the event handler thread it creates, which a connector would do anyways, the multi-loader itself shouldn't be doing anything.

**Comment by alexjhawk** [comment]
@TomKimsey @oliver-walker-hms I will add a class `SCAppArgsParser` to the extensions library which connectors can use to detect if launched by the multi-loader. For example, `new SCAppArgsParser(args).getStartedByMultiLoader()`.

In the event a connector detects the multi-loader launched it, it *must not*:
1. Enable auto-restart functionality, or 
2. Create an event handler

**Comment by alexjhawk** [comment]
> > > What is the performance like? I dont think i saw any documentation mentioning any limitations.
> > 
> > 
> > I didn't do any explicit performance testing, but in general, there should be no hit. Once each main() is invoked, the multi-loader itself finishes. Aside from the event handler thread it creates, which a connector would do anyways, the multi-loader itself shouldn't be doing anything.
> 
> This is more of a concern regarding the fact that even one connector is a lot for the flexy. If someone wanted to run two at once i would think that would risk the jvm becoming unstable.

The idea is that this wouldn't be used by multiple connector applications (although it could be done). The ideal use case is a connector paired with a Java IO server.

**Comment by TomKimsey** [comment]
> > > > What is the performance like? I dont think i saw any documentation mentioning any limitations.
> > > 
> > > 
> > > I didn't do any explicit performance testing, but in general, there should be no hit. Once each main() is invoked, the multi-loader itself finishes. Aside from the event handler thread it creates, which a connector would do anyways, the multi-loader itself shouldn't be doing anything.
> > 
> > 
> > This is more of a concern regarding the fact that even one connector is a lot for the flexy. If someone wanted to run two at once i would think that would risk the jvm becoming unstable.
> 
> The idea is that this wouldn't be used by multiple connector applications (although it could be done). The ideal use case is a connector paired with a Java IO server.

Yeah, i think its probably just important to note the intention. If someone sees this they may be tempted to run two connector apps at once. I think just a warning and/or statement of intent would be helpful in the readme. Something like "Please be aware of the additional processing load that running multiple java applications will put on the JVM. Overloading the JVM may result in instability of the JVM."

**Pull request merged**
